title: coco-data-archive
description: >- 
  This is the webpage of the data archive of the
  Comparing Continous Optimizers (COCO) platform
#url: "numbbo.github.io"
#baseurl: "/data-archive" 
github_repo: "numbbo/data-archive"

# Build settings
theme: just-the-docs
# search_enabled: false # Use this to disable search

plugins:
  - jekyll-feed
  
kramdown:
    math-engine: katex

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md

aux_links:
  "COCO code":
    - "https://github.com/numbbo/coco"
  "data archive":
    - "http://numbbo.github.io/data-archive/"
  "postprocessed data":
    - "http://numbbo.github.io/ppdata-archive/"
  "COCO Home":
    - "http://numbbo.github.io/coco/"
  